### ISSUE TITLE
Callback not called for radio and checkbox menu items

### ISSUE THREAD

**Issue by Thorarin** [anseki/jquery-contextmenu-common#3]
In jQuery contextMenu, each menu item can define their own callback. However, there is also a callback option at the top level, which gets called whenever a menu item doesn't have its own callback function defined.

The functionality that was added in this wrapper doesn't make use of this general callback. For consistency with the base library, it would be better to call it.

Version: jquery-contextmenu-common@1.0.0

**Comment by anseki** [comment]
Hi @Thorarin, thank you for the comment.

Since jQuery.contextMenuCommon wraps jQuery.contextMenu, it should work as jQuery.contextMenu completely, except additional features. That is, the default callback is called when an item does not expose its own callback.

For example:

```js
options1 = {
  selector: '#elm1',

  callback: (key, opt) => {
    console.log('This is default callback');
  },

  items: {

    item1: {
      name: 'Item 1',
      callback: (key, opt) => {
        console.log('This is callback of Item 1');
      }
    },

    item2: {
      name: 'Item 2'
    }
  }
};
```

When you click the `Item 2`, the message `This is default callback` is shown.

**Comment by Thorarin** [comment]
It does, but not for items of type "radio" or "checkbox"...

**Comment by anseki** [comment]
I see, it seems that the default callback is not called because each callback of items of type `checkbox` and `radio` are set by jQuery.contextMenuCommon.
I will fix it soon.

**Comment by anseki** [comment]
I fixed it.
Thank you again 😄
